#define BLOCK_OUTLINE_NONE 0
#define BLOCK_OUTLINE_BLACK 1
#define BLOCK_OUTLINE_WHITE 2
#define BLOCK_OUTLINE_FANCY 3

#define WATER_REFRACTION_NONE 0
#define WATER_REFRACTION_FAST 1
#define WATER_REFRACTION_FANCY 2

#define WATER_WAVE_NONE 0
#define WATER_WAVE_VERTEX 1
#define WATER_WAVE_PARALLAX 2

#define ATMOSPHERE_TYPE_FAST 0
#define ATMOSPHERE_TYPE_FANCY 1

#define MATERIAL_FORMAT_DEFAULT 0
#define MATERIAL_FORMAT_LABPBR 1
#define MATERIAL_FORMAT_OLDPBR 2
#define MATERIAL_FORMAT_PATRIX 3

#define REFLECTION_MODE_NONE 0
#define REFLECTION_MODE_SKY 1
#define REFLECTION_MODE_SCREEN 2

#define SHADOW_TYPE_NONE 0
#define SHADOW_TYPE_BASIC 1
#define SHADOW_TYPE_DISTORTED 2
#define SHADOW_TYPE_CASCADED 3

#define SHADOW_CONTACT_NONE 0
#define SHADOW_CONTACT_FAR 1
#define SHADOW_CONTACT_ALL 2

#define EXPOSURE_MODE_MANUAL 0
#define EXPOSURE_MODE_EYEBRIGHTNESS 1
#define EXPOSURE_MODE_MIPMAP 2
#define EXPOSURE_MODE_HISTOGRAM 3

#define DEBUG_VIEW_GBUFFER_COLOR 1
#define DEBUG_VIEW_GBUFFER_NORMAL 2
#define DEBUG_VIEW_GBUFFER_OCCLUSION 3
#define DEBUG_VIEW_GBUFFER_SPECULAR 4
#define DEBUG_VIEW_GBUFFER_LIGHTING 5
#define DEBUG_VIEW_GBUFFER_SHADOW 6
#define DEBUG_VIEW_SHADOW_COLOR 7
#define DEBUG_VIEW_SHADOW_SSS 8
#define DEBUG_VIEW_SHADOW_DEPTH0 9
#define DEBUG_VIEW_SHADOW_DEPTH1 10
#define DEBUG_VIEW_HDR 11
#define DEBUG_VIEW_LUMINANCE 12
#define DEBUG_VIEW_RSM_COLOR 13
#define DEBUG_VIEW_RSM_NORMAL 14
#define DEBUG_VIEW_RSM_FINAL 15
#define DEBUG_VIEW_BLOOM 16
#define DEBUG_VIEW_PREV_COLOR 17
#define DEBUG_VIEW_PREV_LUMINANCE 18
#define DEBUG_VIEW_WATER_WAVES 19
#define DEBUG_VIEW_DEPTH_TILES 20
#define DEBUG_VIEW_A0 21
#define DEBUG_VIEW_LUT_BRDF 22
#define DEBUG_VIEW_LUT_SUN_TRANSMISSION 23

#define BUFFER_DEFERRED colortex2
#define BUFFER_AO colortex3
#define BUFFER_HDR colortex4
#define BUFFER_HDR_PREVIOUS colortex5
#define BUFFER_LUMINANCE colortex6
#define BUFFER_BLOOM colortex7
#define BUFFER_REFRACT colortex7
#define BUFFER_RSM_COLOR colortex8
#define BUFFER_RSM_DEPTH colortex9
#define BUFFER_BRDF_LUT colortex10
#define BUFFER_WATER_WAVES colortex11
#define BUFFER_DEPTH_PREV colortex12
